### ISSUE TITLE
[Bug]: App window buttons become misaligned when zooming in using cmd+ on Mac

### ISSUE THREAD

**Issue by educbraga** [httpie/desktop#67] opened 2023-02-18 15:26 UTC
### What happened?

Hi!
I have found a bug where the app window buttons become misaligned when zooming in using cmd+ on Mac. This issue occurs on all app windows and can be easily reproduced when using the keyboard zoom command.

The problem appears to be related to the absolute positioning of the buttons, which do not adjust correctly to the window size after zooming. This can be a problem for users who rely on zooming to better view the app content.

A solution would be to remove the gray placeholders for the window buttons.

### Steps to reproduce?

```Markdown
1. Open the app.
2. Press cmd+ to increase the screen zoom.
3. Notice how the buttons in the app window become misaligned with the gray placeholders.
```

### What did you expect to happen?

<img width="125" alt="Screenshot 2023-02-18 at 12 15 13" src="https://user-images.githubusercontent.com/21699905/219873883-fd1ea7b1-5603-4fbb-8782-48752a302d0e.png">

I would expect to not see gray placeholders when I zoom in. 

### Platform

macOS

### HTTPie Desktop version

2023.1.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by janbrasna** [comment] 2023-05-09 18:02
Known issue, possible duplicate of:
- #15

**Closed** 2024-02-13 15:53 UTC
Labels: bug
